- id: '1598828638720'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - platform: webhook
    webhook_id: abcdef
  condition: []
  action:
  - device_id: df00d7c353b5434aa49d76df71565e1d
    domain: light
    entity_id: light.living_room_big_lamp
    type: turn_off
  mode: single
