####################################################################################################
# Package - Log Levels
####################################################################################################

#  Dynamically set the log levels without having to restart HASS or edit configuration.yaml

# Sources:
# https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/logger.yaml
# https://community.home-assistant.io/t/logger-set-level/14267


homeassistant:
  customize_glob:
    "input_select.log_*":
      icon: mdi:bug
      hidden: False

#===================================================================================================
# Input Select 
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/input_select/
#===================================================================================================

input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warn


#===================================================================================================
# Automation
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/automation/
# https://www.home-assistant.io/docs/automation/examples/
#===================================================================================================

automation:
  - alias: Log Level
    initial_state: True
    hide_entity: true
    trigger:
      platform: state
      entity_id:
        - input_select.log_level
#        - input_select.log_component
    action:
      - service: logger.set_level
        data_template:
          homeassistant.components: "{{ states.input_select.log_level.state }}"
      #- service: logger.set_level
      #  data_template:
      #    homeassistant.components: "{{ trigger.to_state.state }}"


#===================================================================================================
# Groups
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/group/
# Icons: https://materialdesignicons.com/
#
# If not using custom Lovelace, groups can be shown in the main dashboard or tabs at the top of the
# overview screen (set 'view: true').
# Groups with actions associated (e.g. switches) will have a group-wide switch at the top by default
# unless we set 'control: hidden'.
# Groups can be referenced as part of other groups too.
#===================================================================================================

# There is only one entity here but at the moment it is the only input_select entity we have so it 
# ends up in it's own card with a switch at the top. So adding to group so that it's not in a card
# with a switch.

group:
  log_level:
    name: Log Level
    #view: false
    #control: hidden
    icon: mdi:bug-outline
    entities:
      - input_select.log_level