####################################################################################################
# Package - Pihole
####################################################################################################

# Sources:
# https://www.home-assistant.io/components/pi_hole/

#===================================================================================================
# Sensors 
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/sensor/
#===================================================================================================

sensor:
  - platform: pi_hole
    name: Pihole Stats
    host: 192.168.0.10:37337
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today

  - platform: command_line
    name: Pihole Status
    command: curl -X GET 'http://192.168.0.10:37337/admin/api.php?status'
    value_template: "{{ value_json.status == 'enabled' }}"



#===================================================================================================
# Groups
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/group/
# Icons: https://materialdesignicons.com/
#
# If not using custom Lovelace, groups can be shown in the main dashboard or tabs at the top of the
# overview screen (set 'view: true').
# Groups with actions associated (e.g. switches) will have a group-wide switch at the top by default
# unless we set 'control: hidden'.
# Groups can be referenced as part of other groups too.
#===================================================================================================

group:
  pihole:
    name: Pihole
    view: false
    control: hidden
    icon: mdi:arrow-decision
    entities:
      - sensor.pihole_status
      - sensor.pihole_stats_ads_blocked_today
      - sensor.pihole_stats_ads_percentage_blocked_today
      - sensor.pihole_stats_dns_queries_today