####################################################################################################
## Package - Alexa Media Player
####################################################################################################

# Source: 
# https://www.home-assistant.io/components/plex/

# Auto discovery didn't work, I think cause it finds the docker IP address instead of the NAS IP.

# Plex component is configured via the plex.conf file. Once it is connected the media_player
# component below will work.

# Plex
#https://www.home-assistant.io/components/plex/
media_player:
  - platform: plex
    show_all_controls: true
    use_episode_art: true
    remove_unavailable_clients: false
    client_remove_interval: 300

#===================================================================================================
# Sensors 
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/sensor/
#===================================================================================================

# This sensor is independant from the Plex component, it should work even if the plex.conf file 
# doesn't properly set up integration.
sensor:
  - platform: plex
    host: 192.168.0.10
    port: 32400
    name: Plex
    #token: KyA5ouMToskXPPmxpBsg
    #ssl: true
    #verify_ssl: false


#===================================================================================================
# Groups
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/group/
# Icons: https://materialdesignicons.com/
#
# If not using custom Lovelace, groups can be shown in the main dashboard or tabs at the top of the
# overview screen (set 'view: true').
# Groups with actions associated (e.g. switches) will have a group-wide switch at the top by default
# unless we set 'control: hidden'.
# Groups can be referenced as part of other groups too.
#===================================================================================================

group:
  plex:
    name: Plex
    view: false
    control: hidden
    icon: mdi:library-video
    entities:
      - sensor.plex
