####################################################################################################
## Package - Ring
####################################################################################################

# Source:
# https://gist.github.com/vidvisionify/ed9352066a9a9d0016cdd30d7489a300

# Set up the ring component in main configuration.yaml file

# This package assumes the name of your camera is 'Front Door'. You may need to change some things
# if it's not.

#===================================================================================================
# Saved this python script in python_scripts folder.
# Make sure 'python_script:' and 'downloader:' are defined in the main configuration.yaml file.
#---------------------------------------------------------------------------------------------------
# # ==== ring_download.py START ====
# # obtain ring doorbell camera object
# # replace the camera.front_door by your camera entity
# ring_cam = hass.states.get('camera.front_door')

# subdir_name = 'ring_{}'.format(ring_cam.attributes.get('friendly_name'))

# # get video URL
# data = {
#     'url': ring_cam.attributes.get('video_url'),
#     'subdir': subdir_name,
#     'filename': ring_cam.attributes.get('friendly_name')
# }

# # call downloader component to save the video
# hass.services.call('downloader', 'download_file', data)
# # ==== ring_download.py END ====

#===================================================================================================
# Binary Sensor
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/sensor/
#===================================================================================================

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion


#===================================================================================================
# Camera
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/camera/
# https://www.home-assistant.io/components/generic/
#===================================================================================================

camera:
  - platform: ring
    ffmpeg_arguments: -pred 1 -q:v 2


#===================================================================================================
# Automation
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/automation/
# https://www.home-assistant.io/docs/automation/examples/
#===================================================================================================

# Download front door video
automation:
  - id: ring_video_download
    alias: Ring Video Download
    initial_state: True
    hide_entity: true
    trigger:
      - platform: template
        value_template: '{{ is_state_attr(''sensor.ring_front_door_last_motion'',
          ''recording_status'', ''ready'') }}'
    action:
      - service: downloader.download_file
        data_template:
          url: '{{ states.camera.front_door.attributes.video_url }}'
          filename: 'ring/{{now().year}}-{{now().month}}.{{now().day}}-{{now().hour}}.{{now().minute}}.mp4'
          overwrite: true

# Download front door image - save as snapshot.jpg so we can always display latest image on dashboard
  - id: ring_image_download_snapshot
    alias: Ring Image Download - Snapshot
    initial_state: True
    hide_entity: true
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
    action:
      - service:  camera.snapshot
        data:
          entity_id: camera.front_door
          filename: 'ring/front_door_snapshot.jpg'
          overwrite: true

# Download front door image
  - id: ring_image_download
    alias: Ring Image Download
    initial_state: True
    hide_entity: true
    trigger:
      - platform: template
        value_template: '{{ is_state_attr(''sensor.ring_front_door_last_motion'',
          ''recording_status'', ''ready'') }}'
    action:
      - service:  camera.snapshot
        data:
          entity_id: camera.front_door
          filename: 'ring/{{now().year}}-{{now().month}}.{{now().day}}-{{now().hour}}.{{now().minute}}.jpg'
          overwrite: true




# Didn't work with triggering using '{{ is_state_attr(''sensor.ring_front_door_last_motion'',
# so trying the motion trigger above.
#
## Download front door image - save as snapshot.jpg so we can always display latest image on dashboard
#  - id: ring_image_download_snapshot
#    alias: Ring Image Download - Snapshot
#    initial_state: True
#    hide_entity: true
#    trigger:
#      - platform: template
#        value_template: '{{ is_state_attr(''sensor.ring_front_door_last_motion'',
#          ''recording_status'', ''ready'') }}'
#    action:
#      - service:  camera.snapshot
#        data:
#          entity_id: camera.front_door
#          filename: '/downloads/front_door_snapshot.jpg'
#          overwrite: true
#
## Download front door image
#  - id: ring_image_download
#    alias: Ring Image Download
#    initial_state: True
#    hide_entity: true
#    trigger:
#      - platform: template
#        value_template: '{{ is_state_attr(''sensor.ring_front_door_last_motion'',
#          ''recording_status'', ''ready'') }}'
#    action:
#      - service:  camera.snapshot
#        data:
#          entity_id: camera.front_door
#          filename: '/downloads/{{now().year}}-{{now().month}}.{{now().day}}-{{now().hour}}.{{now().minute}}.jpg'
#          overwrite: true


# Another non-script option for downloading video
# Source: https://community.home-assistant.io/t/ring-doorbell-download/33244/4
#  - alias: 'Doorbell Motion'
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.ring_front_door_motion
#        from: 'off'
#        to: 'on'
#    action:
#      - service: downloader.download_file
#        data_template:
#          url: "{{ states.camera.front_door.attributes.video_url }}"
#          filename: "last.mpg"
#          overwrite: true

# Play noise on ding
# Source: https://community.home-assistant.io/t/ring-doorbell-download/33244/4
#  - alias: 'Doorbell Ding'
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.ring_front_door_ding
#        from: 'off'
#        to: 'on'
#    action:
#      - service: hassio.addon_stdin
#        data:
#          addon: local_audio_player
#          input: "http://192.168.1.100:8123/local/doorbell-1.mp3"

# Notify on ding
# Source: https://community.home-assistant.io/t/automation-help-ring-doorbell/13683/2
#- alias: 'Doorbell Ding'
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.ring_front_door_ding
#      from: 'off'
#      to: 'on'
#  action:
#   -  service: notify.pushover
#      data_template:
#        title: "Doorbell"
#        message: >-
#          Someone at the door, open it!

# Turn on light with motion detected
# Source: https://community.home-assistant.io/t/turn-a-light-on-when-approaching-the-house/37936/6
#  - id: 'ring_motion_trigger_light'
#    alias: Ring Motion - Light On 30 Sec
#    initial_state: True
#    hide_entity: true
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.ring_front_door_motion
#    condition:
#      - condition: sun
#        after: sunset
#      - condition: state
#        entity_id: light.hall_4
#        state: 'off'
#    action:
#      - service: light.turn_on
#        entity_id: light.hall_4
#      - delay: '00:00:30'
#      - service: light.turn_off
#        entity_id: light.hall_4

#===================================================================================================
# Sensors 
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/sensor/
#===================================================================================================

sensor:
  # Main sensor set up
  - platform: ring

  #  Counting events
  - platform: history_stats
    name: Front Door Motions Today
    entity_id: binary_sensor.ring_front_door_motion
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Front Door Dings Today
    entity_id: binary_sensor.ring_front_door_ding
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Backyard Motions Today
    entity_id: binary_sensor.ring_backyard_motion
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  # Last motion
  - platform: template
    sensors:
      ring_last_motion_front_door:
        friendly_name: Last Motion - Front Door
        icon_template: mdi:walk
        value_template: >-
          {% set today = now().day | int %}
          {% set cat_date = ((as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom("%d")) | int) %}
          {% if today == cat_date %}
          {% set day = "Today" %}
          {% elif (today - 1) == cat_date %}
          {% set day = "Yesterday" %}
          {% elif today == 1 and cat_date > 27 %}
          {% set day = "Yesterday" %}
          {% else %}
          {% set day = as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom("%A")%}
          {% endif %}
          {% set time = as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom("%l:%M %p")%}
          {{[day,time]|join(" ")}}
      ring_last_motion_backyard:
        friendly_name: Last Motion - Backyard
        icon_template: mdi:walk
        value_template: >-
          {% set today = now().day | int %}
          {% set cat_date = ((as_timestamp(states.sensor.ring_backyard_last_motion.attributes.created_at) | timestamp_custom("%d")) | int) %}
          {% if today == cat_date %}
          {% set day = "Today" %}
          {% elif (today - 1) == cat_date %}
          {% set day = "Yesterday" %}
          {% elif today == 1 and cat_date > 27 %}
          {% set day = "Yesterday" %}
          {% else %}
          {% set day = as_timestamp(states.sensor.ring_backyard_last_motion.attributes.created_at) | timestamp_custom("%A")%}
          {% endif %}
          {% set time = as_timestamp(states.sensor.ring_backyard_last_motion.attributes.created_at) | timestamp_custom("%l:%M %p")%}
          {{[day,time]|join(" ")}}
      ring_last_ding_front_door:
        friendly_name: Last Ding
        icon_template: mdi:bell
        value_template: >-
          {% set today = now().day | int %}
          {% set cat_date = ((as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom("%d")) | int) %}
          {% if today == cat_date %}
          {% set day = "Today" %}
          {% elif (today - 1) == cat_date %}
          {% set day = "Yesterday" %}
          {% elif today == 1 and cat_date > 27 %}
          {% set day = "Yesterday" %}
          {% else %}
          {% set day = as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom("%A")%}
          {% endif %}
          {% set time = as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom("%l:%M %p")%}
          {{[day,time]|join(" ")}}


#===================================================================================================
# Groups
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/group/
# Icons: https://materialdesignicons.com/
#
# If not using custom Lovelace, groups can be shown in the main dashboard or tabs at the top of the
# overview screen (set 'view: true').
# Groups with actions associated (e.g. switches) will have a group-wide switch at the top by default
# unless we set 'control: hidden'.
# Groups can be referenced as part of other groups too.
#===================================================================================================

group:
  ring_doorbell:
    name: Ring Doorbell
    view: false
    control: hidden
    icon: mdi:camera-wireless
    entities:
      - sensor.ring_last_ding_front_door
      - sensor.ring_last_motion_front_door
      - sensor.front_door_dings_today
      - sensor.front_door_motions_today
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_last_activity
      - sensor.ring_front_door_battery
      - sensor.ring_front_door_volume
      - sensor.ring_front_door_wifi_signal_category
      - sensor.ring_front_door_wifi_signal_strength
  
  ring_backyard:
    name: Ring Backyard
    view: false
    control: hidden
    icon: mdi:camera-wireless
    entities:
      - sensor.ring_last_motion_backyard
      - sensor.backyard_motions_today
      - binary_sensor.ring_backyard_motion
      - sensor.ring_backyard_last_motion
      - sensor.ring_backyard_last_activity
      - sensor.ring_backyard_battery
      - sensor.ring_backyard_volume
      - sensor.ring_backyard_wifi_signal_category
      - sensor.ring_backyard_wifi_signal_strength
  
  group.ring_chime:
    name: Ring Chime
    view: false
    control: hidden
    icon: mdi:camera-wireless
    entities:
      - sensor.ring_hallway_volume    
      - sensor.ring_hallway_wifi_signal_category
      - sensor.ring_hallway_wifi_signal_strength

