##############################################################
## Package  ##
##############################################################

##########################################################
## Tautulli
#---------------------------------------------------------
## https://www.home-assistant.io/integrations/tautulli/
##########################################################

#===================================================================================================
# Sensors 
#---------------------------------------------------------------------------------------------------
# https://www.home-assistant.io/components/sensor/
#===================================================================================================


sensor:
  - platform: tautulli
    api_key: !secret tautulli_api_key
    host: !secret tautulli_host
    ssl: true

# We can change host in secrets file to use IP:PORT if URL doens't work:
# tautulli_host: 192.168.0.10
# tautulli_port: 8181


